const CHAPTERS=[
  {name:'THE GARDEN',image:'assets/eden.webp',short:'The Garden'},
  {name:'THE JOURNEY',image:'assets/exodus.webp',short:'The Journey'},
  {name:'THE SHEPHERD',image:'assets/shepherd.webp',short:'The Shepherd'},
  {name:'BY THE SEA',image:'assets/galilee.webp',short:'By the Sea'},
  {name:'THE PROMISE',image:'assets/city.webp',short:'The Promise'}
];
const LEVELS=[
  {title:'A new beginning',letters:'OGD',words:[['GO','Move ahead'],['GOD','Creator']],story:'God made the world and called it good. Our journey begins with Him.',ref:'Genesis 1:1–31'},
  {title:'Let there be light',letters:'THGIL',words:[['HI','A greeting'],['LIT','Brightened'],['LIGHT','Shines in darkness']],story:'God spoke, and light appeared. His light helps us see the way.',ref:'Genesis 1:3–5'},
  {title:'Living water',letters:'TAERW',words:[['TEA','A warm drink'],['EAR','Helps us listen'],['WATER','Flows in rivers']],story:'God filled the earth with water and life. Every good gift comes from Him.',ref:'Genesis 1:9–13'},
  {title:'Seeds of kindness',letters:'DSEED',words:[['SEE','Look closely'],['SEED','Plant in the ground'],['DEED','Something you do']],story:'A tiny seed can grow into something wonderful. Kindness grows when we share it.',ref:'Genesis 1:11–12'},
  {title:'The garden path',letters:'DGRANE',words:[['AND','Joins things'],['RAN','Moved quickly'],['GARDEN','A place to grow']],story:'God placed people in a garden to care for His creation.',ref:'Genesis 2:8, 15'},
  {title:'Follow the path',letters:'THAP',words:[['AT','A little word'],['HAT','Worn on a head'],['PATH','A way to walk']],story:'When the road is unfamiliar, God can guide our steps.',ref:'Exodus 13:21–22'},
  {title:'Bread for today',letters:'DBREA',words:[['BE','To exist'],['READ','Look at words'],['BREAD','Food to share']],story:'God gave His people food for each day in the wilderness.',ref:'Exodus 16:4–5'},
  {title:'A cloud above',letters:'UCDLO',words:[['DO','Take action'],['LOUD','Easy to hear'],['CLOUD','Floats in the sky']],story:'A cloud showed the people when to travel and when to rest.',ref:'Exodus 40:36–38'},
  {title:'Keep hoping',letters:'EOPH',words:[['HE','A person'],['HOP','A little jump'],['HOPE','Expect good ahead']],story:'Even on a hard journey, we can remember that God is near.',ref:'Deuteronomy 31:8'},
  {title:'Learning to trust',letters:'TURST',words:[['US','All of us'],['RUST','Brown on metal'],['TRUST','Rely on someone']],story:'The people learned to trust God one day at a time.',ref:'Exodus 16:15–18'},
  {title:'Every sheep matters',letters:'HESPE',words:[['HE','A person'],['SEE','Look closely'],['SHEEP','Part of a flock']],story:'A good shepherd knows each sheep and cares when one is missing.',ref:'John 10:14'},
  {title:'A shepherd’s staff',letters:'FTSAF',words:[['AT','A little word'],['FAST','Quickly'],['STAFF','A shepherd’s stick']],story:'The shepherd leads the flock and helps them along the way.',ref:'Psalm 23:1–4'},
  {title:'The open field',letters:'DLEIF',words:[['IF','A little word'],['LIFE','A gift from God'],['FIELD','Wide grassy land']],story:'Green fields give the flock a safe place to rest.',ref:'Psalm 23:2'},
  {title:'Look and find',letters:'NDFI',words:[['IN','Inside'],['FIN','On a fish'],['FIND','Discover what was lost']],story:'The shepherd searches until the lost sheep is found.',ref:'Luke 15:4–6'},
  {title:'Welcome home',letters:'MEHO',words:[['ME','Myself'],['OH','A word of surprise'],['HOME','A place to belong']],story:'When the sheep returns, there is joy. No one is forgotten.',ref:'Luke 15:6–7'},
  {title:'Into the boat',letters:'OTAB',words:[['AT','A little word'],['OAT','A kind of grain'],['BOAT','Sails on water']],story:'Jesus and His friends crossed the lake in a boat.',ref:'Mark 4:35–36'},
  {title:'A sudden storm',letters:'MSTOR',words:[['OR','A choice'],['MOST','The greatest amount'],['STORM','Wind and rain']],story:'A storm rose on the lake, and the friends felt afraid.',ref:'Mark 4:37–38'},
  {title:'Peace on the water',letters:'CAEPE',words:[['ACE','A playing card'],['CAPE','A cloak'],['PEACE','Calm and safety']],story:'Jesus spoke to the wind and waves, and the lake became calm.',ref:'Mark 4:39'},
  {title:'A full net',letters:'HSFI',words:[['IF','A little word'],['HIS','Belonging to him'],['FISH','Swims in water']],story:'Jesus helped His friends catch fish and called them to follow Him.',ref:'Luke 5:4–11'},
  {title:'Back to shore',letters:'HROSE',words:[['HE','A person'],['HERO','Someone brave'],['SHORE','Land by the water']],story:'On the shore, Jesus welcomed His friends and shared a meal.',ref:'John 21:9–13'},
  {title:'A light to share',letters:'LTHGI',words:[['HI','A greeting'],['LIT','Brightened'],['LIGHT','Helps us see']],story:'Jesus called His followers the light of the world. We can show His love.',ref:'Matthew 5:14–16'},
  {title:'A gift of grace',letters:'EGRAC',words:[['AGE','Years lived'],['CARE','Show kindness'],['GRACE','An undeserved gift']],story:'God’s grace is a gift. We do not earn His love by winning.',ref:'Ephesians 2:8–9'},
  {title:'Loved and known',letters:'DELOV',words:[['DO','Take action'],['DOVE','A peaceful bird'],['LOVE','Deep care'],['LOVED','Cared for']],story:'God loved us first, and we can love others in return.',ref:'1 John 4:19'},
  {title:'Joy for all',letters:'FJLUOY',words:[['JOY','Gladness'],['YOU','The person here'],['JOYFUL','Full of gladness']],story:'Good news brings joy for everyone. Share that joy freely.',ref:'Luke 2:10–11'},
  {title:'A lasting kingdom',letters:'MKGDION',words:[['IN','Inside'],['KIND','Caring'],['GOD','Our Creator'],['KINGDOM','A king’s realm']],story:'Jesus invites us into a kingdom of love, mercy, and hope.',ref:'Matthew 6:33'}
];

const $=id=>document.getElementById(id);
const els={scenery:$('scenery'),chapterName:$('chapterName'),levelTitle:$('levelTitle'),levelLabel:$('levelLabel'),starsLabel:$('starsLabel'),wordBoard:$('wordBoard'),wheel:$('wheel'),trace:$('trace'),traceLine:$('traceLine'),currentWord:$('currentWord'),feedback:$('feedback'),hintCount:$('hintCount'),hintBtn:$('hintBtn'),bottomProgress:$('bottomProgress'),overlay:$('overlay'),overlayScene:$('overlayScene'),overlayTitle:$('overlayTitle'),overlayKicker:$('overlayKicker'),overlayStory:$('overlayStory'),overlayReference:$('overlayReference'),nextBtn:$('nextBtn'),mapOverlay:$('mapOverlay'),mapList:$('mapList'),soundBtn:$('soundBtn')};
const KEY='word-of-life-v1';
function loadSave(){try{const v=JSON.parse(localStorage.getItem(KEY)||'{}');return {unlocked:Math.max(0,Math.min(24,Number(v.unlocked)||0)),completed:Array.isArray(v.completed)?v.completed.filter(i=>Number.isInteger(i)&&i>=0&&i<25):[],hints:Number.isInteger(v.hints)?Math.max(0,Math.min(9,v.hints)):3,sound:v.sound!==false}}catch{return {unlocked:0,completed:[],hints:3,sound:true}}}
let save=loadSave(),index=Math.min(save.unlocked,24),solved=new Set(),selected=[],order=[],pointer=null,gameMode='journey',audioContext=null,feedbackTimer=null;
function persist(){try{localStorage.setItem(KEY,JSON.stringify(save))}catch{}}
function chapter(i=index){return CHAPTERS[Math.floor(i/5)]}
function message(text,type=''){els.feedback.textContent=text;els.feedback.className='feedback '+type;clearTimeout(feedbackTimer);if(type)feedbackTimer=setTimeout(()=>{els.feedback.textContent='Drag across letters or tap them one at a time.';els.feedback.className='feedback'},2600)}
function playTone(freq=650){if(!save.sound)return;try{audioContext ||=new (window.AudioContext||window.webkitAudioContext)();const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type='sine';osc.frequency.setValueAtTime(freq,audioContext.currentTime);gain.gain.setValueAtTime(.045,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.16);osc.connect(gain).connect(audioContext.destination);osc.start();osc.stop(audioContext.currentTime+.17)}catch{}}
function rotateLetters(chars,seed){const a=[...chars].map((ch,i)=>({ch,id:i}));let n=seed*1664525+1013904223;for(let i=a.length-1;i>0;i--){n=(n*1664525+1013904223)>>>0;const j=n%(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
function render(){const level=LEVELS[index],scene=chapter();els.scenery.style.backgroundImage=`url('${scene.image}')`;els.chapterName.textContent=scene.name;els.levelTitle.textContent=level.title;els.levelLabel.textContent=gameMode==='daily'?'TODAY’S PUZZLE':`PUZZLE ${index+1} OF ${LEVELS.length}`;els.starsLabel.textContent=`✦ ${save.completed.length}`;els.hintCount.textContent=save.hints;els.hintBtn.disabled=save.hints<1;els.wordBoard.innerHTML='';level.words.forEach(([word,clue])=>{const row=document.createElement('div');row.className='word-row'+(solved.has(word)?' solved':'');row.innerHTML=`<span class="word-clue"></span><span class="word-slots"></span>`;row.querySelector('.word-clue').textContent=clue;const slots=row.querySelector('.word-slots');for(const char of word){const slot=document.createElement('span');slot.className='slot';slot.textContent=solved.has(word)?char:'';slots.append(slot)}els.wordBoard.append(row)});renderWheel();renderProgress();updateSelection()}
function renderWheel(){els.wheel.replaceChildren();const letters=order.length?order:rotateLetters(LEVELS[index].letters,index+1);order=letters;letters.forEach((tile,i)=>{const angle=-Math.PI/2+i*2*Math.PI/letters.length;const r=letters.length>=7?38:letters.length>=6?36:letters.length>=5?35:34;const b=document.createElement('button');b.type='button';b.className='letter';b.dataset.id=tile.id;b.style.left=`${50+Math.cos(angle)*r}%`;b.style.top=`${50+Math.sin(angle)*r}%`;b.textContent=tile.ch;b.setAttribute('aria-label',`Letter ${tile.ch}, tile ${i+1}`);els.wheel.append(b)});updateSelection()}
function renderProgress(){els.bottomProgress.replaceChildren();const start=Math.floor(index/5)*5;for(let i=start;i<start+5;i++){const b=document.createElement('button');b.type='button';b.className=(i===index?'current':save.completed.includes(i)?'done':'');b.setAttribute('aria-label',`Puzzle ${i+1}${save.completed.includes(i)?', completed':''}`);b.onclick=()=>{if(i<=save.unlocked)startLevel(i)};els.bottomProgress.append(b)}}
function updateSelection(){const ids=new Set(selected);els.wheel.querySelectorAll('.letter').forEach(b=>b.classList.toggle('selected',ids.has(Number(b.dataset.id))));const word=selected.map(id=>order.find(x=>x.id===id).ch).join('');els.currentWord.textContent=word||'Connect the letters';els.currentWord.classList.toggle('empty',!word);drawTrace()}
function drawTrace(){const rect=els.wheel.getBoundingClientRect(),panel=els.wheel.offsetParent,pr=panel.getBoundingClientRect();els.trace.style.left=`${rect.left-pr.left}px`;els.trace.style.top=`${rect.top-pr.top}px`;els.trace.setAttribute('width',rect.width);els.trace.setAttribute('height',rect.height);const points=selected.map(id=>{const b=els.wheel.querySelector(`.letter[data-id="${id}"]`),r=b.getBoundingClientRect();return `${r.left+r.width/2-rect.left},${r.top+r.height/2-rect.top}`});els.traceLine.setAttribute('points',points.join(' '))}
function clearSelection(){selected=[];updateSelection()}
function choose(id){if(selected.includes(id))return;selected.push(id);updateSelection();playTone(420+selected.length*55);if(selected.length>=order.length&&!LEVELS[index].words.some(([w])=>w.startsWith(selected.map(x=>order.find(t=>t.id===x).ch).join(''))&&!solved.has(w)))message('Try another path. You can use each circle once.','bad')}
function submitSelection(){const word=selected.map(x=>order.find(t=>t.id===x).ch).join('');if(!word){message('Tap letters or drag through them first.','bad');return}if(LEVELS[index].words.some(([w])=>w===word&&!solved.has(w)))accept(word);else{message('Try another word. Tap Clear to start over.','bad')}}
function accept(word){if(!LEVELS[index].words.some(([w])=>w===word)||solved.has(word))return;solved.add(word);playTone(850);message(`${word} found!`,'good');clearSelection();render();if(solved.size===LEVELS[index].words.length){setTimeout(completeLevel,450)}}
function completeLevel(){if(gameMode==='journey'&&!save.completed.includes(index)){save.completed.push(index);save.completed.sort((a,b)=>a-b);save.unlocked=Math.max(save.unlocked,Math.min(24,index+1));if(index%5===4)save.hints=Math.min(9,save.hints+2);persist()}const level=LEVELS[index];els.overlayScene.style.backgroundImage=`url('${chapter().image}')`;els.overlayKicker.textContent=gameMode==='daily'?'TODAY’S STORY':index===24?'JOURNEY COMPLETE':'STORY DISCOVERED';els.overlayTitle.textContent=index===24&&gameMode==='journey'?'Your light shines!':'Beautifully done!';els.overlayStory.textContent=level.story;els.overlayReference.textContent=`Explore ${level.ref}`;els.nextBtn.textContent=gameMode==='daily'?'Back to journey':index===24?'Play again':'Next puzzle';els.overlay.classList.remove('hidden');els.nextBtn.focus()}
function startLevel(i,mode='journey'){if(mode==='journey'&&i>save.unlocked)return;index=i;gameMode=mode;solved=new Set();selected=[];order=rotateLetters(LEVELS[index].letters,index+1);els.overlay.classList.add('hidden');els.mapOverlay.classList.add('hidden');render();message('Drag across letters or tap them one at a time.');window.speechSynthesis?.cancel()}
function showMap(){els.mapList.replaceChildren();CHAPTERS.forEach((c,ci)=>{const group=document.createElement('section');group.className='map-group';const h=document.createElement('h3');h.textContent=c.short;group.append(h);const grid=document.createElement('div');grid.className='map-levels';for(let j=0;j<5;j++){const i=ci*5+j,b=document.createElement('button');b.textContent=String(i+1).padStart(2,'0');b.title=LEVELS[i].title;b.setAttribute('aria-label',`Puzzle ${i+1}: ${LEVELS[i].title}${i>save.unlocked?', locked':''}`);b.disabled=i>save.unlocked;b.className=i===index?'active':save.completed.includes(i)?'done':'';b.onclick=()=>startLevel(i);grid.append(b)}group.append(grid);els.mapList.append(group)});const daily=document.createElement('button');daily.className='primary-button daily-button';daily.style.marginTop='16px';daily.style.width='100%';daily.textContent='Play today’s puzzle';daily.onclick=()=>{const day=Math.floor(Date.now()/86400000);startLevel(day%LEVELS.length,'daily')};els.mapList.append(daily);els.mapOverlay.classList.remove('hidden');$('closeMapBtn').focus()}
els.wheel.addEventListener('pointerdown',e=>{const b=e.target.closest('.letter');if(!b)return;e.preventDefault();pointer={id:e.pointerId,started:Number(b.dataset.id),moved:false};els.wheel.setPointerCapture(e.pointerId);choose(Number(b.dataset.id))});
els.wheel.addEventListener('pointermove',e=>{if(!pointer||e.pointerId!==pointer.id)return;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.letter');if(target&&els.wheel.contains(target)){const id=Number(target.dataset.id);if(id!==pointer.started)pointer.moved=true;choose(id)}});
els.wheel.addEventListener('pointerup',e=>{if(!pointer||e.pointerId!==pointer.id)return;const wasDrag=pointer.moved;pointer=null;if(wasDrag&&selected.length>1){const word=selected.map(x=>order.find(t=>t.id===x).ch).join('');if(LEVELS[index].words.some(([w])=>w===word&&!solved.has(w))){accept(word)}else{message('Try another word. Drag through each letter in order.','bad');setTimeout(clearSelection,550)}}});
els.wheel.addEventListener('pointercancel',()=>{pointer=null;clearSelection()});
els.wheel.addEventListener('click',e=>{if(e.detail!==0)return;const b=e.target.closest('.letter');if(b)choose(Number(b.dataset.id))});
window.addEventListener('resize',drawTrace);
$('submitBtn').onclick=submitSelection;
$('clearBtn').onclick=()=>{clearSelection();message('Try another word.')};
$('shuffleBtn').onclick=()=>{order=rotateLetters(LEVELS[index].letters,Math.floor(Math.random()*100000)+1);clearSelection();renderWheel();message('Letters mixed!')};
els.hintBtn.onclick=()=>{if(!save.hints)return;const target=LEVELS[index].words.find(([w])=>!solved.has(w));if(!target)return;const needed=target[0][0],tile=order.find(t=>t.ch===needed);save.hints--;persist();els.hintCount.textContent=save.hints;els.hintBtn.disabled=save.hints===0;const b=els.wheel.querySelector(`.letter[data-id="${tile.id}"]`);b.classList.remove('hint');void b.offsetWidth;b.classList.add('hint');message(`Try a word that starts with ${needed}.`,'good')};
els.soundBtn.onclick=()=>{save.sound=!save.sound;persist();els.soundBtn.textContent=save.sound?'♪':'♪̸';els.soundBtn.setAttribute('aria-label',save.sound?'Turn sound off':'Turn sound on');if(save.sound)playTone()};
$('mapBtn').onclick=showMap;$('homeBtn').onclick=showMap;$('closeMapBtn').onclick=()=>els.mapOverlay.classList.add('hidden');
els.mapOverlay.addEventListener('click',e=>{if(e.target===els.mapOverlay)els.mapOverlay.classList.add('hidden')});
els.nextBtn.onclick=()=>{if(gameMode==='daily')startLevel(save.unlocked);else if(index<24)startLevel(index+1);else startLevel(0)};
$('readBtn').onclick=()=>{if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const speech=new SpeechSynthesisUtterance(els.overlayStory.textContent+' '+els.overlayReference.textContent);speech.rate=.88;window.speechSynthesis.speak(speech)};
window.addEventListener('keydown',e=>{if(e.key==='Escape'){els.mapOverlay.classList.add('hidden');if(!els.overlay.classList.contains('hidden'))return;clearSelection()}if(e.key==='Backspace'&&els.overlay.classList.contains('hidden')&&els.mapOverlay.classList.contains('hidden')){selected.pop();updateSelection()}});
render();
